title: ctfplayer
email: ctfplayer@mail.com
description: > # this means to ignore newlines until "baseurl:"
  What you must learn about computer system is that some of them can be bent. Others can be broken.
url: "https://ctfplayer.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username: ctfplayer

markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
